### ISSUE TITLE
Warning: [react-router] `Router` no longer defaults the history prop to hash history.

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/react-easy-universal#8]
## Reproduce

1. `git clone git@github.com:ericelliott/react-easy-universal.git && cd react-easy-universal`
2. `git fetch --all && git checkout basic-implementation`
3. `npm install`
4. `npm run start:test-server`
5. Open `http://localhost:3000` in your browser
6. View the javascript console

## Result

> Warning: [react-router] `Router` no longer defaults the history prop to hash history. Please use the `hashHistory` singleton instead.

(Note: tests still pass. Maybe there should be a test that fails?)

## Expected

No warnings.

**Comment by ericelliott** [comment]
Fixed in #673f61f

**Comment by sshadmand** [comment]
I still get this warning, but using: 

```
import React from 'react';
import ReactDOM from 'react-dom';
import { Router, hashHistory } from 'react-router';
import routes from './config/routes';

ReactDOM.render(
  <Router histroy={hashHistory}>{routes}</Router>,
  document.getElementById('app')
)
```

Which I believe is the correct imp. on react-router 2.8.1
